// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SystemConfig is the predicate function for systemconfig builders.
type SystemConfig func(*sql.Selector)
