#!/bin/bash
set -e

root_dir="$(dirname "$0")/.."
source "$root_dir/scripts/common.sh"

# check if all servers in cmd folder can be compiled without error
for d in "$root_dir"/cmd/*; do
  if [ -d "$d" ] && [ -f "$d/main.go" ]; then
    target="${d##*/}"
    echo "Building '$target'"

    go_cmd build -o "./cmd/$target/$target" "./cmd/$target"
  fi
done
