// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SystemConfigColumns holds the columns for the "system_config" table.
	SystemConfigColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SystemConfigTable holds the schema information for the "system_config" table.
	SystemConfigTable = &schema.Table{
		Name:       "system_config",
		Columns:    SystemConfigColumns,
		PrimaryKey: []*schema.Column{SystemConfigColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SystemConfigTable,
	}
)

func init() {
	SystemConfigTable.Annotation = &entsql.Annotation{
		Table: "system_config",
	}
}
