// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-nuts/pkg/ent/schema"
	"go-nuts/pkg/ent/systemconfig"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	systemconfigMixin := schema.SystemConfig{}.Mixin()
	systemconfigMixinFields1 := systemconfigMixin[1].Fields()
	_ = systemconfigMixinFields1
	systemconfigFields := schema.SystemConfig{}.Fields()
	_ = systemconfigFields
	// systemconfigDescCreatedAt is the schema descriptor for created_at field.
	systemconfigDescCreatedAt := systemconfigMixinFields1[0].Descriptor()
	// systemconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemconfig.DefaultCreatedAt = systemconfigDescCreatedAt.Default.(func() time.Time)
	// systemconfigDescUpdatedAt is the schema descriptor for updated_at field.
	systemconfigDescUpdatedAt := systemconfigMixinFields1[1].Descriptor()
	// systemconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemconfig.DefaultUpdatedAt = systemconfigDescUpdatedAt.Default.(func() time.Time)
	// systemconfig.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemconfig.UpdateDefaultUpdatedAt = systemconfigDescUpdatedAt.UpdateDefault.(func() time.Time)
}
